### ISSUE TITLE
Breakpad Linux support

### ISSUE THREAD

**Issue by mike-f1** [mike-f1/pioneer#11]
https://github.com/pioneerspacesim/pioneer/issues/3690

**Comment by mike-f1** [comment]
https://github.com/mike-f1/pioneer/tree/breakpad

Seems it compile but:
1. you need to place source in contrib dir, as "exception_handler.h" is under contrib/breakpad/src/src dir
2. you need to configure and make breakpad before compiling pioneer (no automatic way to do this)
3. breakpad needs pthread library: so I added it only for this

...Code is only just started, and it crash to desktop as wanted :)

**Comment by mike-f1** [comment]
It is working: it needs a check for MacOSX and implementing the automatic build system

**Comment by mike-f1** [comment]
I don't know if this could be the "polite" or not, but if @laarmen can do this #3955, I think he could solve this in a matter of second :)

...If not I must learn how these "autotools" works and do by myself... not a problem :( I only have to wait for the will to do it :P

**Comment by laarmen** [comment]
Oh you know I mostly copy n pasted my way through 3955. :-(

**Comment by mike-f1** [comment]
:( ...ok, np: I just tried :D
