### ISSUE TITLE
More varied thruster colours

### ISSUE THREAD

**Issue by mike-f1** [mike-f1/pioneer#12]
https://github.com/pioneerspacesim/pioneer/issues/961

...and also grouping *per direction* as suggested from @nozmajner on IRC

**Comment by mike-f1** [comment]
@fluffyfreak: here I need an help from you, I think you are the top one to solve this:

https://github.com/mike-f1/pioneer/tree/color_and_custom_thrusters

In this branch I bring to thruster color but they refuse to change accordingly, so
instead of *knoking* to Graphics door with my head until something crash (I mean my head :P ),
I felt it is better to ask to someone more skilled than me :)

Feel free to do whatever you feel to do here, from just an hint to a complete rewrite :)

Thank's in advance!

**Comment by mike-f1** [comment]
now it is working: I correct a very very stupid bug and now it is working.

**Comment by impaktor** [comment]
Looks like this can be closed? :smile:

**Comment by mike-f1** [comment]
yes :)
